AWSTemplateFormatVersion: 2010-09-09
Description: API CloudFromation template
Resources:
  # RestApi, authorizer and authorizer rol
  ApiGatewayRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: The API resource
      Name: smalbert-api
  
  # /products Resource
  ApiGatewayProductsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt 
        - ApiGatewayRestApi
        - RootResourceId
      PathPart: products
  
  # /products/{productId} Resource
  ApiGatewayProductResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !Ref ApiGatewayProductsResource
      PathPart: "{productId}"

  # GET /products/{productId}
  ApiGatewayGetProductMethod:
    Type: 'AWS::ApiGateway::Method'
    DependsOn: ProductsAPILambdaPermission
    Properties:
      AuthorizerId: !Ref ApiAuthorizer
      AuthorizationType: COGNITO_USER_POOLS
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayProductResource
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join 
          - ''
          - - 'arn:aws:apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - ProductsAPILambda
              - Arn
            - /invocations
      RequestParameters:
        method.request.header.Authorization: true

  # GET /products
  ApiGatewayGetProductsMethod:
    Type: 'AWS::ApiGateway::Method'
    DependsOn: ProductsAPILambdaPermission
    Properties:
      AuthorizerId: !Ref ApiAuthorizer
      AuthorizationType: COGNITO_USER_POOLS
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayProductsResource
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join 
          - ''
          - - 'arn:aws:apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - ProductsAPILambda
              - Arn
            - /invocations
      RequestParameters:
        method.request.header.Authorization: true

  # Authorizer
  ApiAuthorizer: 
    Type: "AWS::ApiGateway::Authorizer"
    Properties: 
      AuthorizerResultTtlInSeconds: 300
      IdentitySource: method.request.header.Authorization
      Name: CognitoDefaultUserPoolAuthorizer
      ProviderARNs: 
      - !ImportValue smalbert-cognito-user-pool
      RestApiId: !Ref ApiGatewayRestApi
      Type: "AWS_IAM"

  # Deployment of Development Stage
  ApiGatewatDeployment:
    DependsOn:
      - ApiGatewayGetProductsMethod
      - ApiGatewayGetProductMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      Description: Development Stage
      StageName: Development
  
  # Lambda Permission: Gives permition to the api gateway to excecute the Lambda Function
  ProductsAPILambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: !GetAtt 
        - ProductsAPILambda
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref ApiGatewayRestApi
          - /*

  # Lambda backend (golang lambda)
  ProductsAPILambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: ProductsAPI
      Code:
        S3Bucket: !ImportValue lambdas-bucket-name
        S3Key: products-api.zip
      Handler: main
      MemorySize: 128
      Role: !GetAtt 
        - ProductsAPILambdaRole
        - Arn
      Runtime: go1.x
      Timeout: 60

  # Lambda Rol: The rol associated to the Lambda function
  ProductsAPILambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName:
            'Fn::Join':
              - '-'
              - - Ref: 'AWS::StackName'
                - smalbertTablePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:BatchWriteItem'
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/'
                      - Ref: SmalbertTable
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName:
            'Fn::Join':
              - '-'
              - - Ref: 'AWS::StackName'
                - smalbertGSIPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:BatchWriteItem'
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/'
                      - Ref: SmalbertTable
                      - '/index/*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  
  # Database DynamoDB
  SmalbertTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "PartitionKey"
          AttributeType: "S"
        - 
          AttributeName: "SortKey"
          AttributeType: "S"
        - 
          AttributeName: "UserSub"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "PartitionKey"
          KeyType: "HASH"
        - 
          AttributeName: "SortKey"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Smalbert"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "smalbertUserSubGSI"
          KeySchema: 
            - 
              AttributeName: "UserSub"
              KeyType: "HASH"
            - 
              AttributeName: "SortKey"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  
Outputs:
  AwsAccountId:
    Value: !Ref 'AWS::AccountId'
    Description: Account ID of the AWS account
  AwsRegion:
    Value: !Ref 'AWS::Region'
    Description: Region of the AWS deployment
  ApiGatewayRestApi:
    Value: !Ref ApiGatewayRestApi
    Description: Name of the ApiGatewayRestApi
